[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pixel_war = "FtcPZ5sAdSfE8K9suZ98xnhXBBgpnpHXGVu44wXzdtbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "C:/Users/romai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
